# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QHBoxLayout, QMainWindow, QMenu,
    QMenuBar, QSizePolicy, QStatusBar, QTabWidget,
    QToolBar, QVBoxLayout, QWidget)

from HyAn.ui.ui_analysis import Ui_Analysis
from HyAn.ui.ui_pumping_data import Ui_PumpingData
from HyAn.ui.ui_pumping_test import Ui_PumpingTest
import HyAn.ui.icon.rc_icon

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(880, 722)
        MainWindow.setToolButtonStyle(Qt.ToolButtonIconOnly)
        self.t_actionnew = QAction(MainWindow)
        self.t_actionnew.setObjectName(u"t_actionnew")
        icon = QIcon()
        icon.addFile(u":/menu_bar_icon/create file.png", QSize(), QIcon.Normal, QIcon.Off)
        self.t_actionnew.setIcon(icon)
        self.t_actionopen = QAction(MainWindow)
        self.t_actionopen.setObjectName(u"t_actionopen")
        icon1 = QIcon()
        icon1.addFile(u":/menu_bar_icon/open-folder.png", QSize(), QIcon.Normal, QIcon.Off)
        self.t_actionopen.setIcon(icon1)
        self.actionClose_Ctrl_Q_ = QAction(MainWindow)
        self.actionClose_Ctrl_Q_.setObjectName(u"actionClose_Ctrl_Q_")
        self.t_actionsave = QAction(MainWindow)
        self.t_actionsave.setObjectName(u"t_actionsave")
        icon2 = QIcon()
        icon2.addFile(u":/menu_bar_icon/save.png", QSize(), QIcon.Normal, QIcon.Off)
        self.t_actionsave.setIcon(icon2)
        self.m_actionsave_as = QAction(MainWindow)
        self.m_actionsave_as.setObjectName(u"m_actionsave_as")
        self.t_actionprint = QAction(MainWindow)
        self.t_actionprint.setObjectName(u"t_actionprint")
        icon3 = QIcon()
        icon3.addFile(u":/menu_bar_icon/printer.png", QSize(), QIcon.Normal, QIcon.Off)
        self.t_actionprint.setIcon(icon3)
        self.m_actionexit = QAction(MainWindow)
        self.m_actionexit.setObjectName(u"m_actionexit")
        icon4 = QIcon()
        icon4.addFile(u":/menu_bar_icon/exit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.m_actionexit.setIcon(icon4)
        self.t_actioncopy = QAction(MainWindow)
        self.t_actioncopy.setObjectName(u"t_actioncopy")
        icon5 = QIcon()
        icon5.addFile(u":/menu_bar_icon/copy.png", QSize(), QIcon.Normal, QIcon.Off)
        self.t_actioncopy.setIcon(icon5)
        self.t_actionpaste = QAction(MainWindow)
        self.t_actionpaste.setObjectName(u"t_actionpaste")
        icon6 = QIcon()
        icon6.addFile(u":/menu_bar_icon/paste.png", QSize(), QIcon.Normal, QIcon.Off)
        self.t_actionpaste.setIcon(icon6)
        self.m_actiondelete = QAction(MainWindow)
        self.m_actiondelete.setObjectName(u"m_actiondelete")
        icon7 = QIcon()
        icon7.addFile(u":/menu_bar_icon/delete.png", QSize(), QIcon.Normal, QIcon.Off)
        self.m_actiondelete.setIcon(icon7)
        self.m_actionnavigation_panel = QAction(MainWindow)
        self.m_actionnavigation_panel.setObjectName(u"m_actionnavigation_panel")
        self.m_actionnavigation_panel.setCheckable(True)
        self.m_actionnavigation_panel.setChecked(True)
        self.m_actionanalysis_panel = QAction(MainWindow)
        self.m_actionanalysis_panel.setObjectName(u"m_actionanalysis_panel")
        self.m_actionanalysis_panel.setCheckable(True)
        self.m_actionanalysis_status = QAction(MainWindow)
        self.m_actionanalysis_status.setObjectName(u"m_actionanalysis_status")
        self.m_actionanalysis_parameter = QAction(MainWindow)
        self.m_actionanalysis_parameter.setObjectName(u"m_actionanalysis_parameter")
        icon8 = QIcon()
        icon8.addFile(u":/menu_bar_icon/scroll.png", QSize(), QIcon.Normal, QIcon.Off)
        self.m_actionanalysis_parameter.setIcon(icon8)
        self.m_actionScatter_diagram = QAction(MainWindow)
        self.m_actionScatter_diagram.setObjectName(u"m_actionScatter_diagram")
        icon9 = QIcon()
        icon9.addFile(u":/menu_bar_icon/scatter.png", QSize(), QIcon.Normal, QIcon.Off)
        self.m_actionScatter_diagram.setIcon(icon9)
        self.m_actioncreate_a_pumping_test = QAction(MainWindow)
        self.m_actioncreate_a_pumping_test.setObjectName(u"m_actioncreate_a_pumping_test")
        self.m_actioncreate_a_pumping_test_predicition = QAction(MainWindow)
        self.m_actioncreate_a_pumping_test_predicition.setObjectName(u"m_actioncreate_a_pumping_test_predicition")
        self.m_actioncreate_new_analysis = QAction(MainWindow)
        self.m_actioncreate_new_analysis.setObjectName(u"m_actioncreate_new_analysis")
        icon10 = QIcon()
        icon10.addFile(u":/menu_bar_icon/insert.png", QSize(), QIcon.Normal, QIcon.Off)
        self.m_actioncreate_new_analysis.setIcon(icon10)
        self.m_actionfit = QAction(MainWindow)
        self.m_actionfit.setObjectName(u"m_actionfit")
        icon11 = QIcon()
        icon11.addFile(u":/menu_bar_icon/settings.png", QSize(), QIcon.Normal, QIcon.Off)
        self.m_actionfit.setIcon(icon11)
        self.m_actioncomments = QAction(MainWindow)
        self.m_actioncomments.setObjectName(u"m_actioncomments")
        icon12 = QIcon()
        icon12.addFile(u":/menu_bar_icon/comment.png", QSize(), QIcon.Normal, QIcon.Off)
        self.m_actioncomments.setIcon(icon12)
        self.actionDuplicate = QAction(MainWindow)
        self.actionDuplicate.setObjectName(u"actionDuplicate")
        self.m_actioncontent = QAction(MainWindow)
        self.m_actioncontent.setObjectName(u"m_actioncontent")
        icon13 = QIcon()
        icon13.addFile(u":/menu_bar_icon/content.png", QSize(), QIcon.Normal, QIcon.Off)
        self.m_actioncontent.setIcon(icon13)
        self.m_actionweb = QAction(MainWindow)
        self.m_actionweb.setObjectName(u"m_actionweb")
        self.m_actiontutorial = QAction(MainWindow)
        self.m_actiontutorial.setObjectName(u"m_actiontutorial")
        self.m_actionabout = QAction(MainWindow)
        self.m_actionabout.setObjectName(u"m_actionabout")
        icon14 = QIcon()
        icon14.addFile(u":/menu_bar_icon/about.png", QSize(), QIcon.Normal, QIcon.Off)
        self.m_actionabout.setIcon(icon14)
        self.actionRefresh = QAction(MainWindow)
        self.actionRefresh.setObjectName(u"actionRefresh")
        self.actionRefresh.setMenuRole(QAction.NoRole)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_4 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.tab_hydro = QTabWidget(self.centralwidget)
        self.tab_hydro.setObjectName(u"tab_hydro")
        self.tab_hydro.setEnabled(True)
        self.tab_hydro.setMinimumSize(QSize(480, 512))
        self.tab_puming_test = QWidget()
        self.tab_puming_test.setObjectName(u"tab_puming_test")
        self.verticalLayout_10 = QVBoxLayout(self.tab_puming_test)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.wid_pumping_test = Ui_PumpingTest(self.tab_puming_test)
        self.wid_pumping_test.setObjectName(u"wid_pumping_test")

        self.verticalLayout_10.addWidget(self.wid_pumping_test)

        icon15 = QIcon()
        icon15.addFile(u":/menu_bar_icon/pumping_test.png", QSize(), QIcon.Normal, QIcon.Off)
        self.tab_hydro.addTab(self.tab_puming_test, icon15, "")
        self.tab_pumping_data = QWidget()
        self.tab_pumping_data.setObjectName(u"tab_pumping_data")
        self.verticalLayout_2 = QVBoxLayout(self.tab_pumping_data)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.wid_pumping_data = Ui_PumpingData(self.tab_pumping_data)
        self.wid_pumping_data.setObjectName(u"wid_pumping_data")

        self.verticalLayout_2.addWidget(self.wid_pumping_data)

        icon16 = QIcon()
        icon16.addFile(u":/menu_bar_icon/water_wiz.png", QSize(), QIcon.Normal, QIcon.Off)
        self.tab_hydro.addTab(self.tab_pumping_data, icon16, "")
        self.tab_analysis = QWidget()
        self.tab_analysis.setObjectName(u"tab_analysis")
        self.horizontalLayout = QHBoxLayout(self.tab_analysis)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.wid_analysis = Ui_Analysis(self.tab_analysis)
        self.wid_analysis.setObjectName(u"wid_analysis")

        self.horizontalLayout.addWidget(self.wid_analysis)

        icon17 = QIcon()
        icon17.addFile(u":/menu_bar_icon/analysis.png", QSize(), QIcon.Normal, QIcon.Off)
        self.tab_hydro.addTab(self.tab_analysis, icon17, "")

        self.verticalLayout_4.addWidget(self.tab_hydro)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 880, 24))
        self.menu_file = QMenu(self.menubar)
        self.menu_file.setObjectName(u"menu_file")
        self.menu_edit = QMenu(self.menubar)
        self.menu_edit.setObjectName(u"menu_edit")
        self.menu_view = QMenu(self.menubar)
        self.menu_view.setObjectName(u"menu_view")
        self.menu_test = QMenu(self.menubar)
        self.menu_test.setObjectName(u"menu_test")
        self.menu_analysis = QMenu(self.menubar)
        self.menu_analysis.setObjectName(u"menu_analysis")
        self.menu_tools = QMenu(self.menubar)
        self.menu_tools.setObjectName(u"menu_tools")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setEnabled(True)
        self.toolBar.setToolButtonStyle(Qt.ToolButtonIconOnly)
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_edit.menuAction())
        self.menubar.addAction(self.menu_view.menuAction())
        self.menubar.addAction(self.menu_test.menuAction())
        self.menubar.addAction(self.menu_analysis.menuAction())
        self.menubar.addAction(self.menu_tools.menuAction())
        self.menu_file.addAction(self.t_actionnew)
        self.menu_file.addAction(self.t_actionopen)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.t_actionsave)
        self.menu_file.addAction(self.m_actionsave_as)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.t_actionprint)
        self.menu_file.addAction(self.m_actionexit)
        self.menu_edit.addAction(self.t_actioncopy)
        self.menu_edit.addAction(self.t_actionpaste)
        self.menu_edit.addAction(self.m_actiondelete)
        self.menu_view.addAction(self.m_actionnavigation_panel)
        self.menu_view.addSeparator()
        self.menu_view.addAction(self.m_actionanalysis_panel)
        self.menu_view.addAction(self.m_actionanalysis_status)
        self.menu_view.addAction(self.m_actionanalysis_parameter)
        self.menu_view.addAction(self.m_actionScatter_diagram)
        self.menu_test.addAction(self.m_actioncreate_a_pumping_test)
        self.menu_test.addAction(self.m_actioncreate_a_pumping_test_predicition)
        self.menu_analysis.addAction(self.m_actioncreate_new_analysis)
        self.menu_analysis.addSeparator()
        self.menu_analysis.addAction(self.m_actionfit)
        self.menu_analysis.addAction(self.m_actioncomments)
        self.menu_analysis.addSeparator()
        self.menu_tools.addAction(self.m_actioncontent)
        self.menu_tools.addAction(self.m_actionweb)
        self.menu_tools.addAction(self.m_actiontutorial)
        self.menu_tools.addSeparator()
        self.menu_tools.addAction(self.m_actionabout)
        self.toolBar.addAction(self.t_actionnew)
        self.toolBar.addAction(self.t_actionopen)
        self.toolBar.addAction(self.t_actionsave)
        self.toolBar.addAction(self.t_actionprint)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.t_actioncopy)
        self.toolBar.addAction(self.t_actionpaste)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)

        self.tab_hydro.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.t_actionnew.setText(QCoreApplication.translate("MainWindow", u"New", None))
#if QT_CONFIG(tooltip)
        self.t_actionnew.setToolTip(QCoreApplication.translate("MainWindow", u"Create a New File (Ctril+N)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.t_actionnew.setStatusTip(QCoreApplication.translate("MainWindow", u"Create a new file", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.t_actionnew.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.t_actionopen.setText(QCoreApplication.translate("MainWindow", u"Open ", None))
#if QT_CONFIG(tooltip)
        self.t_actionopen.setToolTip(QCoreApplication.translate("MainWindow", u"Open a File(Ctrl+O)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.t_actionopen.setStatusTip(QCoreApplication.translate("MainWindow", u"Open an existing file", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.t_actionopen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionClose_Ctrl_Q_.setText(QCoreApplication.translate("MainWindow", u"Close", None))
#if QT_CONFIG(shortcut)
        self.actionClose_Ctrl_Q_.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.t_actionsave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(tooltip)
        self.t_actionsave.setToolTip(QCoreApplication.translate("MainWindow", u"Save the File(Ctrl+S)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.t_actionsave.setStatusTip(QCoreApplication.translate("MainWindow", u"Save the current file ", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.t_actionsave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.m_actionsave_as.setText(QCoreApplication.translate("MainWindow", u"Save As", None))
#if QT_CONFIG(shortcut)
        self.m_actionsave_as.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.t_actionprint.setText(QCoreApplication.translate("MainWindow", u"Print", None))
#if QT_CONFIG(tooltip)
        self.t_actionprint.setToolTip(QCoreApplication.translate("MainWindow", u"Print(Ctrl+P)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.t_actionprint.setStatusTip(QCoreApplication.translate("MainWindow", u"Print the report ", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.t_actionprint.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
        self.m_actionexit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
#if QT_CONFIG(shortcut)
        self.m_actionexit.setShortcut(QCoreApplication.translate("MainWindow", u"Esc", None))
#endif // QT_CONFIG(shortcut)
        self.t_actioncopy.setText(QCoreApplication.translate("MainWindow", u"Copy ", None))
#if QT_CONFIG(tooltip)
        self.t_actioncopy.setToolTip(QCoreApplication.translate("MainWindow", u"Copy(Ctrl+C)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.t_actioncopy.setStatusTip(QCoreApplication.translate("MainWindow", u"Copy selection to clipboard", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.t_actioncopy.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.t_actionpaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
#if QT_CONFIG(tooltip)
        self.t_actionpaste.setToolTip(QCoreApplication.translate("MainWindow", u"Paste(Ctrl+V)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.t_actionpaste.setStatusTip(QCoreApplication.translate("MainWindow", u"Paste the data from clipboard", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.t_actionpaste.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.m_actiondelete.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
#if QT_CONFIG(shortcut)
        self.m_actiondelete.setShortcut(QCoreApplication.translate("MainWindow", u"Del", None))
#endif // QT_CONFIG(shortcut)
        self.m_actionnavigation_panel.setText(QCoreApplication.translate("MainWindow", u"Navigation Panel", None))
        self.m_actionanalysis_panel.setText(QCoreApplication.translate("MainWindow", u"Analysis Panel", None))
        self.m_actionanalysis_status.setText(QCoreApplication.translate("MainWindow", u"Analysis Status", None))
        self.m_actionanalysis_parameter.setText(QCoreApplication.translate("MainWindow", u"Analysis Parameter", None))
        self.m_actionScatter_diagram.setText(QCoreApplication.translate("MainWindow", u"Scatter Diagram", None))
        self.m_actioncreate_a_pumping_test.setText(QCoreApplication.translate("MainWindow", u"Create a Pumping Test", None))
        self.m_actioncreate_a_pumping_test_predicition.setText(QCoreApplication.translate("MainWindow", u"Create a Pumping Test (Predicition)", None))
        self.m_actioncreate_new_analysis.setText(QCoreApplication.translate("MainWindow", u"Create New Analysis", None))
        self.m_actionfit.setText(QCoreApplication.translate("MainWindow", u"Fit ", None))
        self.m_actioncomments.setText(QCoreApplication.translate("MainWindow", u"Comments", None))
        self.actionDuplicate.setText(QCoreApplication.translate("MainWindow", u"Duplicate", None))
        self.m_actioncontent.setText(QCoreApplication.translate("MainWindow", u"Content", None))
        self.m_actionweb.setText(QCoreApplication.translate("MainWindow", u"Web Help...", None))
        self.m_actiontutorial.setText(QCoreApplication.translate("MainWindow", u"Tutorial...", None))
        self.m_actionabout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionRefresh.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
#if QT_CONFIG(tooltip)
        self.actionRefresh.setToolTip(QCoreApplication.translate("MainWindow", u"Refresh", None))
#endif // QT_CONFIG(tooltip)
        self.tab_hydro.setTabText(self.tab_hydro.indexOf(self.tab_puming_test), QCoreApplication.translate("MainWindow", u"Pumping Test", None))
#if QT_CONFIG(tooltip)
        self.tab_hydro.setTabToolTip(self.tab_hydro.indexOf(self.tab_puming_test), QCoreApplication.translate("MainWindow", u"Project info , Units . Aquifer proerty , Pumping Test", None))
#endif // QT_CONFIG(tooltip)
        self.tab_hydro.setTabText(self.tab_hydro.indexOf(self.tab_pumping_data), QCoreApplication.translate("MainWindow", u"Pumping Data", None))
#if QT_CONFIG(tooltip)
        self.tab_hydro.setTabToolTip(self.tab_hydro.indexOf(self.tab_pumping_data), QCoreApplication.translate("MainWindow", u"Drawdown data , discharge , graph", None))
#endif // QT_CONFIG(tooltip)
        self.tab_hydro.setTabText(self.tab_hydro.indexOf(self.tab_analysis), QCoreApplication.translate("MainWindow", u"Analysis", None))
#if QT_CONFIG(tooltip)
        self.tab_hydro.setTabToolTip(self.tab_hydro.indexOf(self.tab_analysis), QCoreApplication.translate("MainWindow", u"Solution, Output", None))
#endif // QT_CONFIG(tooltip)
        self.menu_file.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menu_edit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menu_view.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menu_test.setTitle(QCoreApplication.translate("MainWindow", u"Test", None))
        self.menu_analysis.setTitle(QCoreApplication.translate("MainWindow", u"Analysis", None))
        self.menu_tools.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
#if QT_CONFIG(statustip)
        self.toolBar.setStatusTip("")
#endif // QT_CONFIG(statustip)
    # retranslateUi

