name: autopep8
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  autopep8:
    # Check if the event is either a pull request or direct push to the main branch
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref || github.ref }}
      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@v2
        with:
          args: --exit-code --recursive --in-place --aggressive --aggressive .
      - name: Commit autopep8 changes
        if: steps.autopep8.outputs.exit-code == 2
        run: |
          git config --global user.name 'Dhanush'
          git config --global user.email 'ibg2501@gmail.com'
          git commit -am "Automated autopep8 fixes"
          git push
