name: Auto-format code with Black

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # replace with the version of Python you are using in your project
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Auto-format code with Black
      run: black .
    - name: Commit changes
      run: |
        git config --global user.name 'Dhanush'
        git config --global user.email 'ibg2501@gmail.com'
        git add -A
        git commit -m "Auto-format code with Black"
        git push origin ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
