name: Auto-format with Black

on:
  push:
    branches: [ main ]
  pull_request_target: 
    types: [opened]

jobs:
  auto-format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          repository: HydroAnalyser/hydro-analyzer
          token: ${{ secrets.TOKEN }}
          ref: ${{ github.ref }}
      - name: Install Black
        run: pip install black
      - name: Auto-format with Black
        run: black .
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add .
          git commit -m "Auto-format with Black"
          git push
